<a href="https://colab.research.google.com/github/UMAIR000001/PyTorch-Week4/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''# 1. Install Git (if needed)
!apt-get install git

# 2. Set your Git username & email (only once)
!git config --global user.email "umairhafeez951@gmail.com"
!git config --global user.name "UMAIR000001"

# 3. Clone your GitHub repo to Colab
!git clone https://github.com/UMAIR000001/PyTorch-Week4.git'''


'# 1. Install Git (if needed)\n!apt-get install git\n\n# 2. Set your Git username & email (only once)\n!git config --global user.email "umairhafeez951@gmail.com"\n!git config --global user.name "UMAIR000001"\n\n# 3. Clone your GitHub repo to Colab\n!git clone https://github.com/UMAIR000001/PyTorch-Week4.git'

In [2]:
print("first day of learning Pytorch")

first day of learning Pytorch


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##  Introduction To Tensors
### Creating Tensors

In [4]:
#scalar
scalar =torch.tensor(5366)
scalar

tensor(5366)

In [5]:
# Check the number of dimensions of vector
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

5366

In [7]:
#Vector
vector=torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [8]:
# Check the number of dimensions of vector
vector.ndim

1

In [9]:
# Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.
vector.shape

torch.Size([5])

In [10]:
#MATRIX
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([1, 2])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR=torch.tensor([[[1,1,1],[2,2,2]]])
TENSOR

tensor([[[1, 1, 1],
         [2, 2, 2]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 2, 3])

# Randon tensors
A random tensor is a multi-dimensional array filled with randomly generated values, created using PyTorch functions like torch.rand(), torch.randn(), or torch.randint().

->These tensors are often used to:

->Simulate input data

->Initialize weights of neural networks

->Test models before using real data

##Different Random Tensor Functions

1:
Function    |	Range of Values             |Data Type
torch.rand()|	Uniform random values [0, 1)|float32


##❓Why are random tensors so valuable in deep learning?
In deep learning, we start with random numbers (random tensors) to initialize model parameters (like weights).
Then the model:

🔁 Looks at data → compares predictions to real values

🔁 Updates the random numbers (weights) using gradients

🔁 Repeats this process until the model learns to make accurate predictions.


## 💡 Why Use Random Tensors Instead of Zero?
If all weights were zero, the model would learn nothing unique (all neurons behave the same).
Randomness breaks symmetry, allowing each neuron to learn something different.

In [17]:
 # Create a random tensor of size (5,2)
#random_tensor=torch.rand(size=(5,3)) == random_tensor=torch.rand(5,3)
random_tensor=torch.rand(size=(5,3))
random_tensor,random_tensor.dtype


(tensor([[0.5873, 0.0168, 0.3431],
         [0.5904, 0.0139, 0.7424],
         [0.7195, 0.5266, 0.2479],
         [0.2164, 0.6405, 0.4335],
         [0.2704, 0.7759, 0.5017]]),
 torch.float32)

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted a random tensor in the common image shape of `[224, 224, 3]` (`[height, width, color_channels`]).
##🧠 Key Point to Remember:
In image processing:

A color image is usually a 3D tensor → height × width × channels

A batch of images becomes a 4D tensor → batch_size × height × width × channels

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
# Summary of all task of  random tensor
demo_tensor=torch.rand(size=(2,5))
demo_tensor,demo_tensor.dtype, demo_tensor.shape,demo_tensor.ndim

(tensor([[0.9352, 0.0806, 0.4038, 0.9673, 0.6434],
         [0.9594, 0.3085, 0.1899, 0.0648, 0.1386]]),
 torch.float32,
 torch.Size([2, 5]),
 2)

# Zeros and Ones

In [20]:
#Creating a tensor all of zeros
# probably used in most cases
zeros_tensor=torch.zeros(2,5)
#Multiplication of Zeros tensor to a random tensor
zeros_tensor*demo_tensor
#zeros_tensor,zeros_tensor.dtype,zeros_tensor.shape,zeros_tensor.ndim

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [21]:
#Creating a tensor all of ones
ones_tensor=torch.ones(2,5)
#Multiplication of Ones tensor to a random tensor
ones_tensor*demo_tensor
#ones_tensor,zeros_tensor.dtype,zeros_tensor.shape,zeros_tensor.ndim

tensor([[0.9352, 0.0806, 0.4038, 0.9673, 0.6434],
        [0.9594, 0.3085, 0.1899, 0.0648, 0.1386]])

#16. Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
zero_to_twenties=torch.arange(start=0,end=21,step=2)
zero_to_twenties

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
#Creating tensors like for ones
one_to_ten_like=torch.ones_like(input=one_to_ten)
one_to_ten_like


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
#Creating tensors like for zeros
one_to_ten_like=torch.zeros_like(input=one_to_ten)
one_to_ten_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Creating tensors like for random tensors here typecasting is required
demo=torch.rand_like(input=one_to_ten,dtype=torch.float32)
demo

tensor([0.0481, 0.7514, 0.8569, 0.4025, 0.1986, 0.4329, 0.3331, 0.7121, 0.8388,
        0.1469])

# 17 Dealing With tensor datatypes

In [27]:
# Default Datatype for tensors is float32 for float values

float_32_tensor=torch.tensor((1.0,2.0,3.0),
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.dtype,float_32_tensor.device,float_32_tensor.requires_grad,float_32_tensor.shape,float_32_tensor.ndim,float_32_tensor

(torch.float32,
 device(type='cpu'),
 False,
 torch.Size([3]),
 1,
 tensor([1., 2., 3.]))

In [28]:
float_32_tensor=torch.tensor([1,2],
                             dtype=torch.float32,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32

# Getting Information for Tensors

#Manipulating tensors (tensor operations)


## Basic operations


In [8]:
import torch

a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

print("Addition Of tensors: ",a+b)
print("Subtraction Of tensors: ",a-b)
print("Multiplication Of tensors: ",a*b)
print("Division Of tensors: ",a/b)



Addition Of tensors:  tensor([5, 7, 9])
Subtraction Of tensors:  tensor([-3, -3, -3])
Multiplication Of tensors:  tensor([ 4, 10, 18])
Division Of tensors:  tensor([0.2500, 0.4000, 0.5000])


## Matrix Multiplication:
This is super important in deep learning — it’s how layers connect to each other.
* In Doing Matrix Multiplication between two  matrices we commonly faced  Shape mismatch erorr therefore for that we use transpose to eliminate that error.


In [32]:
import torch

x = torch.tensor([[1, 2, 3], [1, 2, 3]])  # (2, 3)
y = torch.tensor([[4, 5, 6], [4, 5, 6]])  # (2, 3)

y = y.T  # Transpose y → (3, 2)

result = torch.matmul(x,y)

print("The Matrix Multiplication of x and y is:\n", result)


The Matrix Multiplication of x and y is:
 tensor([[32, 32],
        [32, 32]])


# Transpose of Matrix:
##📌 Main Points:
In deep learning, models learn using matrix operations (like torch.matmul()).

>For matrix multiplication, the number of columns in the first tensor must match the number of rows in the second.

>Transpose adjusts tensor shapes so matrix multiplication becomes possible.

>Used often when:

> >Connecting layers in a neural network

>>Multiplying weight matrices and input tensors

>>Preprocessing input data

In [38]:
x =torch.tensor([[1,2,3],[4,5,6]])

print(f"The shape of matix x is {x.shape}")

x=x.T # Taking Transpose

print(f"The shape of matix x after transpose is {x.shape}")

The shape of matix x is torch.Size([2, 3])
The shape of matix x after transpose is torch.Size([3, 2])


#Finding the min, max, mean, sum, etc (aggregation)

In [56]:
import torch

tensor = torch.tensor([1,2,3,4,5,6])

print("Tensor:\n", tensor)

# Aggregation operations
print("\nMin:",tensor.min())
print("Max:", tensor.max())
print("Sum:", tensor.sum())
print("Mean:", tensor.type(torch.float32).mean())  # mean needs float type
print("Product:",tensor.prod())
print("Standard Deviation:", tensor.type(torch.float32).std())


Tensor:
 tensor([1, 2, 3, 4, 5, 6])

Min: tensor(1)
Max: tensor(6)
Sum: tensor(21)
Mean: tensor(3.5000)
Product: tensor(720)
Standard Deviation: tensor(1.8708)


#Positional min/max
argmax and argmin are used to show the index number of maximum number as well as for Minimum number

In [62]:
demo_tensor=torch.arange(start=0,end=21,step=2)

print(f"The tensor elements are : {demo_tensor}")

print(f"THe Index of Maximum element in our tensor is {torch.argmax(demo_tensor)}")

print(f"THe Index of Maximum element in our tensor is {torch.argmin(demo_tensor)}")


The tensor elements are : tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
THe Index of Maximum element in our tensor is 10
THe Index of Maximum element in our tensor is 0
tensor(20)


#Change tensor datatype:
A common issue with deep learning operations is having your tensors in different datatypes.
so practicing changing the data type of a tensor

In [71]:
# 🔹 Step 1: Initialize a tensor from 0 to 9
tensor_A = torch.arange(start=0, end=10, step=1)

# 🔹 Step 2: Check its original data type
print(f"The tensor is {tensor_A} with the original datatype: {tensor_A.dtype}")

# 🔹 Step 3: Change its data type explicitly to float32
tensor_A = tensor_A.type(torch.float32)

# 🔹 Step 4: Print the updated tensor and its new data type
print(f"The tensor is {tensor_A} with the updated datatype: {tensor_A.dtype}")


The tensor is tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) with the original datatype: torch.int64
The tensor is tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) with the updated datatype: torch.float32


#Reshaping, stacking, squeezing and unsqueezing:
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.
 >These 4 concepts — reshaping, stacking, squeezing, and unsqueezing — are very important in PyTorch for organizing tensor shapes before feeding them into a neural network

##Reshaping
You can reshape into any size as long as:

product of dimensions
=
total number of elements
product of dimensions=total number of elements
in the below example number of elements are 9 and product of dimension is also 9 (3*3)

In [89]:
x=torch.arange(9)

print(f"The tensor is {x} and its shape is {x.shape}")


#Reshaping
reshape_x=x.reshape(3,3)

print(f"\nThe tensor is {x} and its shape is {reshape_x.shape}")


The tensor is tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) and its shape is torch.Size([9])

The tensor is tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) and its shape is torch.Size([3, 3])


## You can add an Extra Dimension in a tensor

In [84]:
x=torch.arange(8)

print(f"The tensor is {x} and its shape is {x.shape } and the number of Dimension is {x.ndim}")


#Adding an extra Dimension

reshape_x=x.reshape(1,8)

print(f"The tensor is {x} and its shape is {x.shape } and the number of Dimension is {x.ndim}")

# torch.view

We can also change the view with torch.view().
>Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

#torch.stack():

>If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [ ]:
x=torch.arange(1,6)
print(f"Original Tensor is {x}")

print("stacking horizontally:")
torch.stack([x,x,x],dim=0)

In [ ]:
x=torch.arange(1,6)
print(f"Original Tensor is {x}")

print("stacking vertically:")
torch.stack([x,x,x],dim=1)

#torch.squeeze():

>To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

## torch.unsqueeze():
> And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.
How about removing all single dimensions from a tensor?

In [ ]:
x=torch.arange(6)
print(f"The original tensor is {x} having shape {x.shape}")

# Reshpaing the original tenosr
print("\nUsing reshape funtion to add an extra dimension")
reshape_x=x.reshape(1,6)
print(f"The Reshape of x  tensor is {reshape_x} having the shape {reshape_x.shape}")

#squeezing
print("\nPerofrming Squeezing Function")
new=torch.squeeze(reshape_x)
print(f"the tensor {new} and having the new shape  {new.shape}")

#unsqueezing
print("\nPerofrming UnSqueezing Function")
new=new.unsqueeze(dim=0)
print(f"the tensor {new} and having the new shape  {new.shape}")


#torch.permute(input, dims):
permute() is used to reorder dimensions (useful in images: [C, H, W] → [H, W, C])
>You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

>Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.
> Remember ! 🔹 permute() is used only on multi-dimensional tensors, like 2D, 3D, etc.


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

In [ ]:
#permute is also like tanspose
x = torch.rand(2, 3)
print(x)
# shape is (rows=2, cols=3)
print(x.permute(1, 0))


#Indexing (selecting data from tensors):
>Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

>To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

##1D Tensor (like array):

In [2]:
x = torch.tensor([10, 20, 30, 40])
print(x[0])  # 👉 10 (first element)
print(x[2])  # 👉 30 (third element)


tensor(10)
tensor(30)


#2D Tensor (matrix):
Let’s take this matrix (2 rows, 3 columns):

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])


In [ ]:
# 1️⃣ Select first row
print("x[0] =", x[0])         # 👉 tensor([11, 12, 13])

# 2️⃣ Select second row, third column
print("x[1][2] =", x[1][2])   # 👉 23

# 3️⃣ Select all rows, column 0
print("x[:, 0] =", x[:, 0])   # 👉 tensor([11, 21, 31])

# 4️⃣ Select row 2, all columns
print("x[2, :] =", x[2, :])   # 👉 tensor([31, 32, 33])

# 5️⃣ Select element at row 0, column 1
print("x[0, 1] =", x[0, 1])   # 👉 12


# Indexing in a 3D Tensor

In [ ]:
import torch

# 🧠 Creating a 3D Tensor (2 blocks, each with 2 rows and 3 columns)
x3 = torch.tensor([
    [   # 🔲 Block 0
        [1, 2, 3],   # Row 0 of Block 0
        [4, 5, 6]    # Row 1 of Block 0
    ],
    [   # 🔲 Block 1
        [7, 8, 9],    # Row 0 of Block 1
        [10, 11, 12]  # Row 1 of Block 1
    ]
])

# 🔎 Tensor structure:
# Block 0 --> [[1, 2, 3], [4, 5, 6]]
# Block 1 --> [[7, 8, 9], [10, 11, 12]]

# ✅ Shape of the 3D tensor
print("Shape of x3:", x3.shape)  # 👉 torch.Size([2, 2, 3])
# Meaning:
# 2 blocks (depth), each block has 2 rows, and each row has 3 columns

# 📌 Indexing examples for clarity:

# Get Block 0 (first 2D matrix)
print("x3[0] →\n", x3[0])  # 👉 [[1, 2, 3], [4, 5, 6]]

# Get Row 0 from Block 1
print("x3[1][0] →", x3[1][0])  # 👉 [7, 8, 9]

# Get specific element: Block 1 → Row 1 → Column 2
print("x3[1][1][2] →", x3[1][1][2])  # 👉 12


#Summary of 3D tenosr:
🧠 Summary (copy into notes):
x3.shape = [2, 2, 3]
→ 2 blocks
→ Each block has 2 rows
→ Each row has 3 columns

x3[0] → Block 0

x3[1][0] → Block 1, Row 0

x3[1][1][2] → Block 1, Row 1, Column 2 → 12

#PyTorch tensors & NumPy
##🔄 Think of it like this:
NumPy is a very popular library used in data science and machine learning.

PyTorch is built to work easily with NumPy — because both are used to work with numerical data.

>So, PyTorch lets you:

Convert NumPy array → PyTorch tensor

Convert PyTorch tensor → NumPy array

This helps you move data back and forth depending on what you're working on.

In [ ]:
# 🔁 NumPy ↔️ PyTorch Conversion

import numpy as np
import torch

# NumPy array → PyTorch tensor
np_array = np.array([10, 20, 30])
torch_tensor = torch.from_numpy(np_array)

print("Torch Tensor:", torch_tensor)  # 👉 tensor([10, 20, 30])

# PyTorch tensor → NumPy array
back_to_numpy = torch_tensor.numpy()

print("NumPy Array:", back_to_numpy)  # 👉 [10 20 30]

# 🧠 Notes:
# - torch.from_numpy() = NumPy → PyTorch
# - tensor.numpy() = PyTorch → NumPy
# - Both share the same memory (changing one will affect the other)
