<a href="https://colab.research.google.com/github/UMAIR000001/PyTorch-Week4/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Install Git (if needed)
!apt-get install git

# 2. Set your Git username & email (only once)
!git config --global user.email "umairhafeez951@gmail.com"
!git config --global user.name "UMAIR000001"

# 3. Clone your GitHub repo to Colab
!git clone https://github.com/UMAIR000001/PyTorch-Week4.git


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Cloning into 'PyTorch-Week4'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.


In [80]:
print("first day of learning Pytorch")

first day of learning Pytorch


In [81]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##  Introduction To Tensors
### Creating Tensors

In [82]:
#scalar
scalar =torch.tensor(5366)
scalar

tensor(5366)

In [83]:
# Check the number of dimensions of vector
scalar.ndim

0

In [84]:
# Get tensor back as python int
scalar.item()

5366

In [85]:
#Vector
vector=torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [86]:
# Check the number of dimensions of vector
vector.ndim

1

In [87]:
# Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.
vector.shape

torch.Size([5])

In [88]:
#MATRIX
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [89]:
MATRIX.ndim

2

In [90]:
MATRIX[0]

tensor([1, 2])

In [91]:
MATRIX.shape

torch.Size([2, 2])

In [92]:
#TENSOR
TENSOR=torch.tensor([[[1,1,1],[2,2,2]]])
TENSOR

tensor([[[1, 1, 1],
         [2, 2, 2]]])

In [79]:
TENSOR.ndim

3

In [93]:
TENSOR.shape

torch.Size([1, 2, 3])

# Randon tensors