# NumPy Practice
- It helps Python to handle Large Scale Numerical Operation efficiently
- It is build in C 


In [1]:
!pip install numpy

In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [9]:
my_list=[1,2,3,4,5]

print("list:",my_list*2)# Not Support Vectorised Operations

print(type(my_list))


list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
<class 'list'>
It is an array:  [ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [10]:
#inilaizing NumPy array
array=np.array([1,2,3,4,5])
print("It is an array: ",array*2)
print(type(array))

It is an array:  [ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
array=np.array(1)
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

1
0
()


In [17]:
import numpy as np
array=np.array([[1],[2],[3]])
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

[[1]
 [2]
 [3]]
2
(3, 1)


In [19]:
import numpy as np
array=np.array([['A','B','C']
                ,['D','E','F']
                ,['G','H','I']])
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2
(3, 3)


In [22]:
array=np.array([1,2,3,4,5])
print(array)
print(array.ndim) # 1d array
print(array.shape) # 1D array having only 5 elements 


[1 2 3 4 5]
1
(5,)


In [36]:
array=np.array([[1,2,3],[4,5,6]])
print(array)
print(array.ndim) # 2d array
print(array.shape) # 2D array having 2 rows and 3 colums (2,3)
print(array[1][1]) 



[[1 2 3]
 [4 5 6]]
2
(2, 3)
5


In [49]:
array=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums
print(array[0][0][2]) # Chain Indexing Method
print(array[0,0,2]) #Called Multi-Indexing Method


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
3
3


# Exersises of Multi_Dimensional Indexing 

In [ ]:
array=np.array([['A','B','C','D','E','F','G','H','I','J','K','L','M'],
              ['N','O','P','Q','R','S','T','U','V','W','X','Y','Z']])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums

# Exersise use Multi_Dimensional Indexing to write your name
print(array[1,7]+array[0,12]+array[0,0]+array[0,8]+array[1,4])

In [59]:
array=np.array([
                [['A','B','C','D','E'],
                 ['F','G','H','I','J'],
                 ['K','L','M','N','O'],
                 ['P','Q','R','S','T']],
    
                [['U','V','W','X','Y'],
                 ['Z','Z','Z','Z','Z'],
                ['Z','Z','Z','Z','Z'],
                ['Z','Z','Z','Z','Z']]])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums

# Exersise use Multi_Dimensional Indexing to write your name
print(array[1,0,0]+array[0,2,2]+array[0,0,0]+array[0,1,3]+array[0,3,2])

[[['A' 'B' 'C' 'D' 'E']
  ['F' 'G' 'H' 'I' 'J']
  ['K' 'L' 'M' 'N' 'O']
  ['P' 'Q' 'R' 'S' 'T']]

 [['U' 'V' 'W' 'X' 'Y']
  ['Z' 'Z' 'Z' 'Z' 'Z']
  ['Z' 'Z' 'Z' 'Z' 'Z']
  ['Z' 'Z' 'Z' 'Z' 'Z']]]
3
(2, 4, 5)
UMAIR


# Slicing 

In [101]:
import numpy as np
array=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])

# array[start:end:steps] here end will always  be exclusive 
# Accessing rows
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [104]:
# Accessing rows
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
# Accessing rows
print(array[0:3:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [112]:
# Accessing all rows with specific colums
print(array[:,0])# accessing all rows first colum value

[ 1  5  9 13]


In [113]:
# Accessing all rows with specific colums
print(array[:,0:3])# accessing all rows first colum values to third colum values

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [114]:
# Accessing all rows with specific colums
print(array[:,0:3:2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [116]:
# Accessing all rows with specific colums
print(array[:,0:4:3]) 

[[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]
