# This Notebook serves as an introduction to the NumPy Python library.

-  introduction to NumPy 🔢
-  multidimensional arrays 🧊
-  slicing ✂️
-  arithmetic ✖️
-  broadcasting 📡
-  aggregate functions 📊
-  filtering 🧲
-  random numbers 🎲

# NumPy Practice
- It helps Python to handle Large Scale Numerical Operation efficiently.
- It is build in C .


In [1]:
!pip install numpy

In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [117]:
my_list=[1,2,3,4,5]

print("list:",my_list*2)# Not Support Vectorised Operations

print(type(my_list))


list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
<class 'list'>


In [10]:
#inilaizing NumPy array
array=np.array([1,2,3,4,5])
print("It is an array: ",array*2)
print(type(array))

It is an array:  [ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
array=np.array(1)
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

1
0
()


In [17]:
import numpy as np
array=np.array([[1],[2],[3]])
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

[[1]
 [2]
 [3]]
2
(3, 1)


In [19]:
import numpy as np
array=np.array([['A','B','C']
                ,['D','E','F']
                ,['G','H','I']])
print(array) # Value
print(array.ndim) # Number of Dimensions
print(array.shape) #shape

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2
(3, 3)


In [118]:
array=np.array([1,2,3,4,5])
print(array)
print(array.ndim) # 1d array
print(array.shape) # 1D array having only 5 elements 


[1 2 3 4 5]
1
(5,)


In [36]:
array=np.array([[1,2,3],[4,5,6]])
print(array)
print(array.ndim) # 2d array
print(array.shape) # 2D array having 2 rows and 3 colums (2,3)
print(array[1][1]) 



[[1 2 3]
 [4 5 6]]
2
(2, 3)
5


In [49]:
array=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums
print(array[0][0][2]) # Chain Indexing Method
print(array[0,0,2]) #Called Multi-Indexing Method


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
3
3


# Exersises of Multi_Dimensional Indexing 

In [119]:
array=np.array([['A','B','C','D','E','F','G','H','I','J','K','L','M'],
              ['N','O','P','Q','R','S','T','U','V','W','X','Y','Z']])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums

# Exersise use Multi_Dimensional Indexing to write your name
print(array[1,7]+array[0,12]+array[0,0]+array[0,8]+array[1,4])

[['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M']
 ['N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']]
2
(2, 13)
UMAIR


In [120]:
array=np.array([
                [['A','B','C','D','E'],
                 ['F','G','H','I','J'],
                 ['K','L','M','N','O'],
                 ['P','Q','R','S','T']],
    
                [['U','V','W','X','Y'],
                 ['Z','Z','Z','Z','Z'],
                ['Z','Z','Z','Z','Z'],
                ['Z','Z','Z','Z','Z']]])
print(array)
print(array.ndim) # 3d array
print(array.shape) # 3D array having 2 layers(matrices),2 rows and 3 colums

# Exersise use Multi_Dimensional Indexing to write your name
print(array[1,0,0]+array[0,2,2]+array[0,0,0]+array[0,1,3]+array[0,3,2])

[[['A' 'B' 'C' 'D' 'E']
  ['F' 'G' 'H' 'I' 'J']
  ['K' 'L' 'M' 'N' 'O']
  ['P' 'Q' 'R' 'S' 'T']]

 [['U' 'V' 'W' 'X' 'Y']
  ['Z' 'Z' 'Z' 'Z' 'Z']
  ['Z' 'Z' 'Z' 'Z' 'Z']
  ['Z' 'Z' 'Z' 'Z' 'Z']]]
3
(2, 4, 5)
UMAIR


# Slicing 


### Formula is : array[start:end:steps]

In [122]:
import numpy as np
array=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])

# array[start:end:steps] here end will always  be exclusive 
# Accessing rows
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [123]:
# Accessing rows
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
# Accessing rows
print(array[0:3:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [112]:
# Accessing all rows with specific colums
print(array[:,0])# accessing all rows first colum value

[ 1  5  9 13]


In [113]:
# Accessing all rows with specific colums
print(array[:,0:3])# accessing all rows first colum values to third colum values

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [114]:
# Accessing all rows with specific colums
print(array[:,0:3:2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [124]:
# Accessing all rows with specific colums
print(array[:,0:4:3]) 

[[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]


# Arithematic 

In [132]:
# Scalar Arithematic
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("------------Following are Scalar Arithematic Operations---------")

print("Addition by 1",arr1+1)
print("Subtraction by 1",arr1-1)
print("Multiplication by 2",arr1*2)
print("Division by 2",arr1/2)
print("Power by 2",arr1**2)

------------Following are Scalar Arithematic Operations---------
Addition by 1 [2 3 4 5 6]
Subtraction by 1 [0 1 2 3 4]
Multiplication by 2 [ 2  4  6  8 10]
Division by 2 [0.5 1.  1.5 2.  2.5]
Power by 2 [ 1  4  9 16 25]


In [133]:
# Vectorized Math Funcs
arr1=np.array([1,2,3,4,5])

print("------------Following are Vectorized Math Funtions Examples---------")

print("The Square root Funtion:",np.sqrt(arr1))
print("Rounding each element in the array:",np.round(arr1))
print("Rounding each element upside:",np.ceil(arr1))
print("Rounding each element downside:",np.floor(arr1))

------------Following are Vectorized Math Funtions---------
[1.         1.41421356 1.73205081 2.         2.23606798]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [135]:
# Element-Wise  Arithematic
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("------------Following are Element-Wise Arithematic Operations---------")

print("Addition by 1: ",arr1+arr2)
print("Subtraction by 1: ",arr1-arr2)
print("Multiplication by 2: ",arr1*arr2)
print("Division by 2: ",arr1/arr2)
print("Power by 2: ",arr1**arr2)

------------Following are Element-Wise Arithematic Operations---------
Addition by 1:  [ 7  9 11 13 15]
Subtraction by 1:  [-5 -5 -5 -5 -5]
Multiplication by 2:  [ 6 14 24 36 50]
Division by 2:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power by 2:  [      1     128    6561  262144 9765625]


# BroadCasting
- 👉 Broadcasting = stretching a smaller array so it can work with a bigger array.

- 👉 NumPy does this automatically when shapes don’t match — but are still compatible.

In [141]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[1],[2],[3],[4],[5]])

print("---------Array 1 Properties----------")
print(arr1)
print(arr1.shape)
print(arr1.ndim)

print("---------Array 2 Properties----------")
print(arr2)
print(arr2.shape)
print(arr2.ndim)

print("------------Applying Broadcasting at arr1 and arr2------------\n ")
print(arr1*arr2)

---------Array 1 Properties----------
[[1 2 3 4 5]]
(1, 5)
2
---------Array 2 Properties----------
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
2
------------Applying Broadcasting at arr1 and arr2------------
 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


# Exersise 
- Do broadcasting  on matrix order (4,5) and (4,1)

In [147]:
arr1=np.array([[1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5]])
arr2=np.array([[1],[2],[3],[4]])

print("---------Array 1 Properties----------")
print(arr1)
print(arr1.shape)
print(arr1.ndim)

print("---------Array 2 Properties----------")
print(arr2)
print(arr2.shape)
print(arr2.ndim)

print("------------Applying Broadcasting at arr1 and arr2------------\n ")
print(arr1*arr2)

---------Array 1 Properties----------
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
(4, 5)
2
---------Array 2 Properties----------
[[1]
 [2]
 [3]
 [4]]
(4, 1)
2
------------Applying Broadcasting at arr1 and arr2------------
 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]]


# Aggregate Funtions

In [148]:
array1=np.array([1,2,3,4,5])
print(np.sum(array1))

15


In [162]:
array1=np.array([[1,2,3,4,0],
                 [1,2,3,4,0]]) 
#Suming  all from the Colums
print(np.sum(array1,axis=0))


[2 4 6 8 0]


In [165]:

# Suming all from the Rows
print(np.sum(array1,axis=1))

[10 10]


In [154]:
# Calculating Mean
print(np.mean(array1))

3.1


In [156]:
# Calculating Standard Deviation
print(np.std(array1))

1.57797338380595


In [159]:
# Calculating Variance
print(np.var(array1))

2.4899999999999998


In [ ]:
# Calculating Minimum value
print(np.min(array1))

In [166]:
# Calculating Maximum value 
print(np.max(array1))

4


In [168]:
# Calculating the position Minimum value
print(np.argmin(array1))

4


In [169]:
# Calculating the position Maximum value 
print(np.argmax(array1))

3


# Filtering in NumPy:
- It refers to the process of selecting elements from an array that matches a given condition

In [190]:
ages=np.array([[21,17,19,20,22,16,30,65],
                [39,22,15,99,18,19,20,17]])
# Finding teenagers in the given array
teenagers=ages[ages<18]
print("The teenagers in the given array are : ",teenagers)


The teenagers in the given array are :  [17 16 15 17]


In [194]:
# Finding Adults in the given array
adults=ages[ages>=18]
print("The Adults in the given array are : ",adults)


The Adults in the given array are :  [21 19 20 22 30 65 39 22 99 18 19 20]


In [195]:
# Finding seniors in the given array
seniors=ages[ages>=60]
print("The Seniors in the given array are : ",seniors)

The Seniors in the given array are :  [65 99]


In [193]:
# Finding in the given array ages of people from 20 and 29 only
adults=ages[(ages>=20) & (ages<=29)]
print("The Adults in the given array are : ",adults)

The Adults in the given array are :  [21 20 22 22 20]


# Exersise :
 * make a new array  where teenagers and  seniors people ages are present only  

In [203]:
teenagers_seniors=ages[(ages<18) | (ages>=60)]
print(print("The Ages of Teenagers and seniors are :",teenagers_seniors))

The Ages of Teenagers and seniors are : [17 16 65 15 99 17]
None


-   make a new array where even ages are present only likewise for old ages

In [209]:
# Even Ages Code
even_ages=ages[ages%2==0]
print("Even Ages are :",even_ages)

Even Ages are : [20 22 16 30 22 18 20]


In [210]:
# Odd Ages Code
odd_ages=ages[ages%2==1]
print("odd Ages are :",odd_ages)

odd Ages are : [21 17 19 65 39 15 99 19 17]


# Usage of Where Funtion:

In [215]:
ages=np.array([[21,17,19,20,22,16,30,65],
                [39,22,15,99,18,19,20,17]])

adults=np.where(ages>=18,ages,0)
print("Adults Ages are :",adults) 

Adults Ages are : [[21  0 19 20 22  0 30 65]
 [39 22  0 99 18 19 20  0]]


In [222]:
teenagers=np.where(ages<18,ages,0)
print("Teenagers Ages are :",teenagers)

Teenagers Ages are : [[ 0 17  0  0  0 16  0  0]
 [ 0  0 15  0  0  0  0 17]]
[[21 17 19 20 22 16 30 65]
 [39 22 15 99 18 19 20 17]]


# Random Numbers 

### Integers 

In [245]:
# Here Generating a single number between 1 and 10  
rng=np.random.default_rng()
print(rng.integers(low=1,high=11))

2


In [255]:
# generating random numbers with custimize Size
print(rng.integers(low=1,high=11,size=(2,3)))

[[ 8  2  4]
 [ 2  5 10]]


In [256]:
#  generating random numbers with custimize Size (2D) with seed (To control the Randomness)
rng=np.random.default_rng(seed=1)
print(rng.integers(low=1,high=11,size=(3,3)))

[[ 5  6  8]
 [10  1  2]
 [ 9 10  3]]


### Generating Floating point numbers

In [257]:
# Generating simple decicmal number in 1D
print(np.random.uniform(low=-1,high=1))

-0.604218811842681


In [258]:
# Generating decicmal numbers of size 3 (three randam numbers)  in 1D
print(np.random.uniform(low=-1,high=1,size=3))

[0.04359051 0.30240035 0.30480523]


In [262]:
# Generating simple decicmal number in 2D
print(np.random.uniform(low=-1,high=1,size=(3,4)))

[[ 0.78921333 -0.82991158 -0.92189043 -0.66033916]
 [ 0.75628501 -0.80330633 -0.15778475  0.91577906]
 [ 0.06633057  0.38375423 -0.36896874  0.37300186]]


In [273]:
# Generating random decimal numbers with Eliminating  Randomness 
np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1,size=(5,5)))

[[ 0.30717917 -0.76998611  0.90056573 -0.0356172   0.74494907]
 [-0.57533464 -0.91858075 -0.20561108 -0.53373561  0.68348145]
 [-0.58583531  0.48493907 -0.21569174 -0.63548696  0.48707883]
 [-0.86083584  0.77067441  0.9052888   0.86228687 -0.16913809]
 [-0.94203668  0.96405497 -0.32072463  0.41337439 -0.27624586]]


### Shuffling an Array:

In [280]:
rng=np.random.default_rng()
array=np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)


[1 4 3 2 5]


# Exersise

###  Randomly selecting any element from an Array

In [291]:
fruits=np.array(['Apply','Orange' ,'Banana','Coconut','Pinapple'])
Fruits=rng.choice(fruits)
print(Fruits)

Banana


In [294]:
# Randomly selecting three fruits at a time 1D
Fruits=rng.choice(fruits ,size=3)
print(Fruits)

['Pinapple' 'Orange' 'Apply']


In [295]:
# Randomly selecting  Fruits in 2D
Fruits=rng.choice(fruits,size=(3,3))
print(Fruits)

[['Banana' 'Apply' 'Pinapple']
 ['Orange' 'Coconut' 'Banana']
 ['Pinapple' 'Banana' 'Pinapple']]


### Fun Exersie  do above add emojis in place of just  fruits name

In [296]:
fruits=np.array(['🍎','🍌','🍊','🍍','🥥'])
Fruits=rng.choice(fruits)
print(Fruits)

🥥


In [ ]:
# Randomly selecting three fruits at a time 1D
Fruits=rng.choice(fruits ,size=3)
print(Fruits)

In [298]:
# Randomly selecting  Fruits in 2D
Fruits=rng.choice(fruits,size=(3,3))
print(Fruits)

[['🥥' '🍎' '🥥']
 ['🍊' '🍌' '🥥']
 ['🍊' '🍎' '🍎']]


In [312]:
# Randomly selecting  Fruits in 2D 
rng=np.random.default_rng(seed=1)
Fruits=rng.choice(fruits,size=(3,3))
print(Fruits)

[['🍊' '🍊' '🍍']
 ['🥥' '🍎' '🍎']
 ['🥥' '🥥' '🍌']]
